"""empty message

Revision ID: 1f57157eb709
Revises: bb32a1d42ccd
Create Date: 2023-05-28 09:53:06.971726

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1f57157eb709'
down_revision = 'bb32a1d42ccd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('enterprise',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('enterprise',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
